#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use YusamHub\DbExt\PdoExtMigrations;

$pdoExt = db_ext_mysql_pdo_ext_create_from_config(include __DIR__ . "/config/config.php");

$mySqlPdoExtMigrations = new PdoExtMigrations($pdoExt, __DIR__ . '/migrations/mix', __DIR__ . "/tmp/migrations.txt");
$mySqlPdoExtMigrations->migrate();
